version: "3"

services:
  v2ray:
    image: v2fly/v2fly-core:latest
    container_name: v2ray
    restart: always
    volumes:
      - /usr/local/etc/v2ray:/usr/local/etc/v2ray
    ports:
      - "443:443"
    # command: ["v2ray","-config=https://xxx.com"]

  v2scar:
    container_name: v2scar
    image: fgo987/v2scar:1.0
    restart: always
    depends_on:
      - v2ray
    links:
      - v2ray
    environment:
      V2SCAR_SYNC_TIME: 60
      V2SCAR_API_ENDPOINT: ""
      V2SCAR_GRPC_ENDPOINT: "v2ray:8080"
